apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: database
spec:
  containers:
  - name: database
    image: mysql:latest
    ports:
    - name: mysql-port
      containerPort: 3306
