apiVersion: v1
kind: Pod
metadata:
  name: web-service-01
  labels:
    app: web-server
    tier: node-01
spec:
  containers:
    - name: nodejs-app
      image: teddy1565/kubernetes-demo-01:v0.0.1
      ports:
      - name: web-server-port
        containerPort: 3000

