apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-deployment
  labels:
    app: basic-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: basic-deployment
  template:
    metadata:
      labels:
        app: basic-deployment
    spec:
      containers:
      - name: my-pod
        image: teddy1565/docker-demo
        ports:
        - containerPort: 3000
