apiVersion: v1
kind: Pod
metadata:
  name: basic-pod
  labels:
    app: webserver
    tier: backend
spec:
  containers:
  - name: nodejs-app
    image: teddy1565/docker-demo
    ports:
    - containerPort: 3000
